### ISSUE TITLE
Some links swapped between Normalized and KeyValues flavours

### ISSUE THREAD

**Issue by fbattello** [smart-data-models/dataModel.Agrifood#8]
Hello,

Some links are swapped between Normalized and KeyValues flavours.

It's the case for [Agrifarm](https://github.com/smart-data-models/dataModel.Agrifood/tree/master/AgriFarm), but I suspect there may be other places where it happens.

The NGSI-LD kv/normalized examples "embedded" in the [spec](https://github.com/smart-data-models/dataModel.Agrifood/blob/master/AgriFarm/doc/spec.md) are swapped.

The 2 examples links are swapped : [link1](https://smart-data-models.github.io/dataModel.Agrifood/AgriFarm/examples/example-normalized.jsonld) and [link2](https://smart-data-models.github.io/dataModel.Agrifood/AgriFarm/examples/example.jsonld).

There's a last more subtle diff.
The `hasAgriParcel` Relationship isn't modelled the same way [here](https://smart-data-models.github.io/dataModel.Agrifood/AgriFarm/examples/example.jsonld) (array of objects) and in the spec example (array of values).

**Comment by albertoabellagarcia** [comment]
you're completely right, we have reviewed all of them, and most were misplaced. 
thank you very much
Fixed
